name: dartdocorg
description: Generates the Dart documentation for all the packages in pub
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  args: ^0.13.5
  googleapis_auth: ^0.2.3
  googleapis_beta: ^0.30.1
  googleapis: ^0.31.0
  http: ^0.11.3
  intl: ^0.13.0
  logging: ^0.11.3
  path: ^1.3.9
  pub_semver: ^1.3.0
  stack_trace: ^1.6.6
  yaml: ^2.1.10
  tasks: ^0.1.0
  resource: ^1.1.0
dev_dependencies:
  grinder: ^0.8.0
  linter: any
  test: ^0.12.15
  tuneup: ^0.2.4
